name: Continuous Integration

on: [push]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

  steps:
    - name: Checkout the repository
      uses: actions/checkout@v3.1.0
      with:
        ref: main

    - id: version
      name: Get Version
